### ISSUE TITLE
KeyError on TS-251+ / 4.3.6

### ISSUE THREAD

**Issue by cerebrate** [colinodell/python-qnapstats#35] opened 2020-01-20 04:00 UTC
**Device Model Number**: TS-251+

**QTS Version**: 4.3.6.0993

This is the continuation issue for the KeyError I mentioned over in https://github.com/home-assistant/home-assistant/issues/30980; traceback repeated from there:

```
2020-01-19 13:19:05 ERROR (SyncWorker_0) [homeassistant.components.qnap.sensor] Failed to fetch QNAP stats from the NAS
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/qnap/sensor.py", line 191, in update
    self.data["system_stats"] = self._api.get_system_stats()
  File "/usr/local/lib/python3.7/site-packages/qnapstats/qnap_stats.py", line 207, in get_system_stats
    force_list=("DNS_LIST")
  File "/usr/local/lib/python3.7/site-packages/qnapstats/qnap_stats.py", line 67, in _get_url
    self._init_session()
  File "/usr/local/lib/python3.7/site-packages/qnapstats/qnap_stats.py", line 49, in _init_session
    if self._login() is False:
  File "/usr/local/lib/python3.7/site-packages/qnapstats/qnap_stats.py", line 57, in _login
    result = self._execute_post_url("authLogin.cgi", data, False)
  File "/usr/local/lib/python3.7/site-packages/qnapstats/qnap_stats.py", line 98, in _execute_post_url
    return self._handle_response(resp, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/qnapstats/qnap_stats.py", line 112, in _handle_response
    auth_passed = data['authPassed']
KeyError: 'authPassed'
```

XML response from freshly-cloned debug.py is as follows:

**XML/Debug Output:**

~~~
<QDocRoot version="1.0">
<doQuick><![CDATA[]]></doQuick><is_booting><![CDATA[0]]></is_booting><mediaReady><![CDATA[1]]></mediaReady><shutdown_info><type><![CDATA[-1]]></type><timestamp><![CDATA[0]]></timestamp><duration><![CDATA[0]]></duration></shutdown_info>
<SMBFW><![CDATA[0]]></SMBFW><model><modelName><![CDATA[TS-X51]]></modelName><internalModelName><![CDATA[TS-X51]]></internalModelName><platform><![CDATA[TS-NASX86]]></platform><platform_ex><![CDATA[X86_BAYTRAIL]]></platform_ex><customModelName><![CDATA[]]></customModelName><displayModelName><![CDATA[TS-251+]]></displayModelName><sas_model><![CDATA[0]]></sas_model><storage_v2>1</storage_v2>     <encryptfsSupported><![CDATA[1]]></encryptfsSupported></model>
<firmware><version><![CDATA[4.3.6]]></version><number><![CDATA[0993]]></number><build><![CDATA[20190704]]></build><patch><![CDATA[0]]></patch><buildTime><![CDATA[2019/07/04]]></buildTime></firmware>
<rfs_bits><![CDATA[64]]></rfs_bits><specVersion><![CDATA[1.0]]></specVersion><hostname><![CDATA[mnemosyne]]></hostname><DemoSiteSuppurt><![CDATA[no]]></DemoSiteSuppurt><customLogo><customFrontLogo><![CDATA[]]></customFrontLogo><customLoginLogo><![CDATA[]]></customLoginLogo></customLogo>
<HTTPHost><![CDATA[mnemosyne.arkane-systems.lan]]></HTTPHost><webAccessPort><![CDATA[8080]]></webAccessPort><QWebPort><![CDATA[80]]></QWebPort><webFSEnabled><![CDATA[1]]></webFSEnabled><QMultimediaEnabled><![CDATA[0]]></QMultimediaEnabled><MSV2Supported><![CDATA[0]]></MSV2Supported><MSV2WebEnabled><![CDATA[1]]></MSV2WebEnabled><MSV2URL><![CDATA[/MSV2/]]></MSV2URL><QDownloadEnabled><![CDATA[1]]></QDownloadEnabled><DSV2Supported><![CDATA[0]]></DSV2Supported><DSV3Supported><![CDATA[1]]></DSV3Supported><DSV2URL><![CDATA[/downloadstation/?ssid=]]></DSV2URL><QWebEnabled><![CDATA[1]]></QWebEnabled><QWebSSLEnabled><![CDATA[0]]></QWebSSLEnabled><QWebSSLPort><![CDATA[8081]]></QWebSSLPort><NVREnabled><![CDATA[0]]></NVREnabled><NVRURL><![CDATA[/surveillance/]]></NVRURL><NVRVER><![CDATA[1]]></NVRVER><WFM2><![CDATA[1]]></WFM2><wfmPortEnabled><![CDATA[0]]></wfmPortEnabled><wfmPort><![CDATA[8080]]></wfmPort><wfmSSLEnabled><![CDATA[0]]></wfmSSLEnabled><wfmSSLPort><![CDATA[443]]></wfmSSLPort><wfmURL><![CDATA[/filestation/]]></wfmURL><QMusicsEnabled><![CDATA[0]]></QMusicsEnabled><QMusicsURL><![CDATA[/musicstation/]]></QMusicsURL><QVideosEnabled><![CDATA[0]]></QVideosEnabled><QVideosURL><![CDATA[/videostation/]]></QVideosURL><QPhotosEnabled><![CDATA[0]]></QPhotosEnabled><QPhotosURL><![CDATA[/photostation/]]></QPhotosURL><stunnelEnabled><![CDATA[1]]></stunnelEnabled><stunnelPort><![CDATA[443]]></stunnelPort><forceSSL><![CDATA[1]]></forceSSL><HDAROOT_ALMOST_FULL><![CDATA[0]]></HDAROOT_ALMOST_FULL><passwdConstraints><passwdConstraint01><![CDATA[1]]></passwdConstraint01><passwdConstraint02><![CDATA[1]]></passwdConstraint02><passwdConstraint03><![CDATA[1]]></passwdConstraint03><passwdConstraint04><![CDATA[0]]></passwdConstraint04></passwdConstraints>
<ts><![CDATA[10867949]]></ts><fwNotice><![CDATA[0]]></fwNotice><title><![CDATA[]]></title><content><![CDATA[]]></content><psType><![CDATA[1]]></psType><standard_massage><![CDATA[WARNING: This is a secure system. Do not login without proper authorization. Unauthorized use will be prosecuted.]]></standard_massage><standard_color><![CDATA[#FFFFFF]]></standard_color><standard_size><![CDATA[12 px]]></standard_size><standard_bg_style><![CDATA[fill]]></standard_bg_style><showVersion><![CDATA[1]]></showVersion><show_link><![CDATA[1]]></show_link><cuid><![CDATA[c459ad9a8e414b891aefacf275853183]]></cuid></QDocRoot>
~~~

**Comment by colinodell** [comment] 2020-02-24 20:00
It looks like the TS-251+ does not follow the standard convention of retuning an `authPassed` element and a session ID in the response.  In order to get this model working, I'd need you to do some reverse engineering of the AJAX calls being made in the QNAP admin area to figure out the authentication flow, as it might be different - especially the parts where the frontend retreives the session ID and uses that in subsequent AJAX calls.

**Comment by colinodell** [comment] 2020-02-24 20:02
This seems to be a duplicate of https://github.com/colinodell/python-qnapstats/issues/25, so let's close this and move the discussion over there :)

**Closed by colinodell** 2020-02-24 20:02 UTC
Labels: help wanted, unsupported model
